[workspace]
resolver = "2"
members = ["crates/prochist-core", "bin/prochist-cli", "bin/prochist-tui"]

[workspace.package]
version = "0.2.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/y4nettechi/prochist"

[workspace.dependencies]
clap = { version = "4.6", features = ["derive"] }
crossterm = "0.29"
ratatui = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
trycmd = "1.2"
snapbox = "1.2"
windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_RestartManager",
    "Win32_System_Threading",
] }

[profile.release]
lto = true
