name: CD

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  upload-assets:
    name: ${{ matrix.bin }}-${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - bin: ph
            package: prochist-cli
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - bin: ph
            package: prochist-cli
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - bin: phi
            package: prochist-tui
            target: x86_64-pc-windows-msvc
            os: windows-latest
          - bin: phi
            package: prochist-tui
            target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
    timeout-minutes: 30
    env:
      PACKAGE_MATCH: ${{ startsWith(github.event.release.name, format('{0}-v', matrix.package)) }}
    steps:
      - name: Checkout repository
        if: env.PACKAGE_MATCH == 'true'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Install Rust toolchain
        if: env.PACKAGE_MATCH == 'true'
        uses: dtolnay/rust-toolchain@stable
      - name: Static CRT on MSVC
        if: env.PACKAGE_MATCH == 'true' && endsWith(matrix.target, 'windows-msvc')
        shell: bash
        run: echo "RUSTFLAGS=-C target-feature=+crt-static" >> "${GITHUB_ENV}"
      - name: Build and upload binary
        if: env.PACKAGE_MATCH == 'true'
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: ${{ matrix.bin }}
          target: ${{ matrix.target }}
          tar: all
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
